version: '3.9'

services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #     - redis
  #   command: npm run start:dev

  # worker:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.dev
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis
  #     - postgres
  #   command: npm run start:worker

  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
      POSTGRES_DB: shop
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
